name: hydroutils
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - black
  - hydroerr
# for dev
  - pip
  - bump2version
  - wheel
  - watchdog
  - flake8
  - tox
  - coverage
  - Sphinx
  - twine
  - grip
  - pytest
  - pytest-runner