name: hydroutils
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - xarray
  - numba
  - tzfpy
  # for plotting
  - matplotlib
  - seaborn
  # for gis plotting
  - cartopy
  - tqdm
  - hydroerr
  - async-retriever
  - rich
  # for s3 access
  - boto3
  - minio
  - s3fs
  # for dev
  - black
  - bump2version
  - wheel
  - watchdog
  - flake8
  - tox
  - coverage
  - Sphinx
  - twine
  - grip
  - pytest
  - pytest-runner
  # for pypi package
  - pip