name: hydroutils
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - tzfpy
  # for plotting
  - matplotlib
  - seaborn
  # for gis plotting
  - cartopy
  - tqdm
  - black
  - hydroerr
  - async-retriever
  - rich
  # for s3 access
  - boto3=1.34.34
  - minio
  - s3fs=2024.2
  # for dev
  - bump2version
  - wheel
  - watchdog
  - flake8
  - tox
  - coverage
  - Sphinx
  - twine
  - grip
  - pytest
  - pytest-runner
  # for pypi package
  - pip