site_name: hydroutils

site_url: https://zhuanglaihong.github.io/hydroutils

repo_url: https://github.com/zhuanglaihong/hydroutils

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
        #   ignore_h1_titles: True
        #   execute: True
        #   execute_ignore: "*.ipynb"
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Getting Started:
          - Installation: installation.md
          - Quick Start: usage.md
          - FAQ: faq.md
    - API Reference:
          - Overview: api/hydroutils.md
          - Core Modules:
              - Statistical Analysis: api/hydro_stat.md
              - Visualization: api/hydro_plot.md
              - Time Processing: api/hydro_time.md
              - File Operations: api/hydro_file.md
          - Advanced Modules:
              - Mathematical Operations: api/hydro_arithmetric.md
              - AWS S3 Integration: api/hydro_s3.md
              - Logging Utilities: api/hydro_log.md
    - Development:
          - Contributing: contributing.md
          - Changelog: changelog.md
          - Report Issues: https://github.com/OuyangWenyu/hydroutils/issues

remote_name: upstream
