name: docs
on:
    push:
        branches:
            - dev

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install uv and setup venv
              run: |
                  curl -LsSf https://astral.sh/uv/install.sh | sh
                  uv --version
                  uv venv
                  source .venv/bin/activate

            - name: Install dependencies with uv
              run: |
                  source .venv/bin/activate
                  uv sync
                  uv add mkdocstrings 
                  uv add mkdocs-material 
                  uv add mkdocs-jupyter
                # uv pip sync requirements.txt
                # uv pip install --upgrade minio argon2-cffi-bindings
                #   
                #   uv add mkdocstrings-python-legacy 
                #   uv add mkdocs-git-revision-date-plugin 
                #   uv add mkdocs-jupyter 
                #   uv add ipykernel

            - name: Deploy docs
              run: |
                  source .venv/bin/activate
                  export JUPYTER_PLATFORM_DIRS=1
                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@github.com"
                  mkdocs gh-deploy --force
